spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bangdong?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true
    username: root
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name:
      BangDong
